gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - '#e78284'
      - bold
    inactiveBorderColor:
      - '#a5adce'
    optionsTextColor:
      - '#8caaee'
    selectedLineBgColor:
      - '#ccaaaa'
    cherryPickedCommitBgColor:
      - '#51576d'
    cherryPickedCommitFgColor:
      - '#e78284'
    unstagedChangesColor:
      - '#e78284'
    defaultFgColor:
      - '#000000'
    searchingActiveBorderColor:
      - '#e5c890'

  authorColors:
    '*': '#babbf1'
    'Raymond W. Ko': '#ff0000'
